#!/usr/bin/env python3
"""
"Since You Checked" orchestrator.

Run:  python3 -m scripts.changes.update            (from the repo root)
      python3 -m scripts.changes.update --only news,lake
      python3 -m scripts.changes.update --dry-run  (fetch + diff, write nothing)

Each run:
  1. snapshot() every source module (independent failures keep last good state)
  2. diff() new state against data/changes/state.json
  3. append events to data/changes/changes.json (pruned to KEEP_DAYS)
  4. archive the raw snapshot in data/changes/snapshots/ (keep last KEEP_SNAPSHOTS)
  5. rewrite data/changes/daily-changes.md — the newsletter's raw material

The page (changes.html) only ever reads changes.json and filters client-side
by the visitor's stored last-visit time.
"""

import argparse
import importlib
import json
import os
import sys
import traceback

from .common import now_utc, iso, CATEGORIES, serialize_state

SOURCE_MODULES = [
    "weather",        # NWS alerts + forecast heads-up
    "lake",           # city beach tracker status changes
    "roads",          # BTV construction map + VT511 incidents
    "transit",        # GMT service alerts
    "civic",          # CivicClerk meeting agendas
    "news",           # local newsroom + city hall RSS (food news routed to 🍽)
    "chatter",        # r/burlington hot posts
    "events_local",   # newly added events from data/events.json
]

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
CHANGES_DIR = os.path.join(ROOT, "data", "changes")
STATE_PATH = os.path.join(CHANGES_DIR, "state.json")
LOG_PATH = os.path.join(CHANGES_DIR, "changes.json")
SNAP_DIR = os.path.join(CHANGES_DIR, "snapshots")
MD_PATH = os.path.join(CHANGES_DIR, "daily-changes.md")

KEEP_DAYS = 7          # events older than this fall off the page anyway
KEEP_SNAPSHOTS = 30    # raw snapshot archive depth


def load_json(path, default):
    try:
        with open(path) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return default


def save_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        json.dump(data, f, indent=1, ensure_ascii=False)
        f.write("\n")
    os.replace(tmp, path)


def prune_log(events, now):
    from datetime import timedelta
    cutoff = iso(now - timedelta(days=KEEP_DAYS))
    return [e for e in events if e["ts"] >= cutoff]


def dedupe(events, existing):
    """Drop events already in the log (same source + headline + url)."""
    seen = {(e["source"], e["headline"], e["url"]) for e in existing}
    fresh = []
    for e in events:
        key = (e["source"], e["headline"], e["url"])
        if key not in seen:
            seen.add(key)
            fresh.append(e)
    return fresh


def write_markdown(events, now):
    """daily-changes.md — last 24h of change lines, grouped, newsletter-ready."""
    from datetime import timedelta
    from zoneinfo import ZoneInfo
    tz = ZoneInfo("America/New_York")
    cutoff = iso(now - timedelta(hours=24))
    recent = sorted(
        (e for e in events if e["ts"] >= cutoff),
        key=lambda e: (-e["priority"], e["ts"]), reverse=False,
    )
    lines = [
        f"# What changed in Burlington — {now.astimezone(tz).strftime('%A, %B %-d, %Y')}",
        "",
        f"_Auto-generated by the Since You Checked pipeline at {now.astimezone(tz).strftime('%-I:%M %p')}. "
        "Change lines from the last 24 hours, biggest first — raw material for the newsletter._",
        "",
    ]
    if not recent:
        lines.append("_A quiet day: no tracked changes in the last 24 hours._")
    by_cat = {}
    for e in recent:
        by_cat.setdefault(e["category"], []).append(e)
    order = sorted(by_cat, key=lambda c: (-max(e["priority"] for e in by_cat[c]), -len(by_cat[c])))
    for cat in order:
        meta = CATEGORIES[cat]
        lines.append(f"## {meta['icon']} {meta['label']}")
        lines.append("")
        for e in sorted(by_cat[cat], key=lambda e: (-e["priority"], e["ts"]), reverse=False):
            t = e["ts"][11:16]
            frag = f"- **{e['headline']}**"
            if e.get("detail"):
                frag += f" — {e['detail']}"
            if e.get("url", "").startswith("http"):
                frag += f" ([{e['sourceName']}]({e['url']}))"
            else:
                frag += f" ({e['sourceName']})"
            lines.append(frag)
        lines.append("")
    with open(MD_PATH, "w") as f:
        f.write("\n".join(lines).rstrip() + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="comma-separated module names")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    modules = SOURCE_MODULES
    if args.only:
        modules = [m for m in SOURCE_MODULES if m in args.only.split(",")]

    now = now_utc()
    state = load_json(STATE_PATH, {})
    log = load_json(LOG_PATH, {"generated": None, "events": []})

    new_events = []
    snapshot_record = {"taken": iso(now), "sources": {}}
    failures = []

    for name in modules:
        try:
            mod = importlib.import_module(f".sources.{name}", package=__package__)
        except Exception:
            print(f"[{name}] IMPORT FAILED", file=sys.stderr)
            traceback.print_exc()
            failures.append(name)
            continue
        prev = state.get(mod.ID)
        try:
            cur = serialize_state(mod.snapshot())
        except Exception as e:
            print(f"[{name}] snapshot failed, keeping last good state: {e}", file=sys.stderr)
            failures.append(name)
            snapshot_record["sources"][mod.ID] = {"ok": False, "error": str(e)[:300]}
            continue
        bootstrap = prev is None
        try:
            events = mod.diff(prev, cur, bootstrap)
        except Exception:
            print(f"[{name}] diff failed", file=sys.stderr)
            traceback.print_exc()
            failures.append(name)
            continue
        state[mod.ID] = cur
        snapshot_record["sources"][mod.ID] = {"ok": True, "state": cur}
        new_events.extend(events)
        print(f"[{name}] ok — {len(events)} change(s){' (bootstrap)' if bootstrap else ''}")

    fresh = dedupe(new_events, log["events"])
    log["events"] = prune_log(sorted(log["events"] + fresh, key=lambda e: e["ts"]), now)
    log["generated"] = iso(now)

    print(f"\n{len(fresh)} new event(s), {len(log['events'])} in the {KEEP_DAYS}-day log, "
          f"{len(failures)} source failure(s){': ' + ', '.join(failures) if failures else ''}")

    if args.dry_run:
        for e in fresh:
            print(f"  [{e['category']}] {e['headline']}")
        return

    save_json(STATE_PATH, state)
    save_json(LOG_PATH, log)

    os.makedirs(SNAP_DIR, exist_ok=True)
    snap_name = now.strftime("%Y-%m-%dT%H%M%SZ") + ".json"
    save_json(os.path.join(SNAP_DIR, snap_name), snapshot_record)
    snaps = sorted(os.listdir(SNAP_DIR))
    for old in snaps[:-KEEP_SNAPSHOTS]:
        os.remove(os.path.join(SNAP_DIR, old))

    write_markdown(log["events"], now)
    print(f"wrote {os.path.relpath(LOG_PATH, ROOT)}, snapshots/{snap_name}, daily-changes.md")


if __name__ == "__main__":
    main()
